// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ScrubBot.Data;
using System;

namespace ScrubBot.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ScrubBot.Data.Guild", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("CharPrefix");

                    b.Property<string>("StringPrefix");

                    b.HasKey("Id");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("ScrubBot.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("GuildId");

                    b.Property<string>("Nickname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ScrubBot.Data.User", b =>
                {
                    b.HasOne("ScrubBot.Data.Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildId");
                });
#pragma warning restore 612, 618
        }
    }
}
